<?php get_header(); ?>
<main>
<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">پلتفرم آموزش آنلاین</span><h1>یاد بگیر، <span class="gradient">بساز و بدرخش</span> 🚀</h1><p>دوره‌های حرفه‌ای برنامه‌نویسی، هوش مصنوعی و مهارت‌های دیجیتال برای کودکان و نوجوانان؛ با پروژه‌های واقعی و کلاس آنلاین.</p><div class="actions"><a class="btn btn-primary" href="#courses">مشاهده دوره‌ها</a><a class="btn btn-light" href="<?php echo esc_url(wp_registration_url()); ?>">ثبت‌نام رایگان</a></div></div><div class="hero-art"><div class="floating float-one">🎓 <strong>یادگیری هوشمند</strong><br><small>مسیر مخصوص هر دانش‌آموز</small></div><div class="hero-icon">💻</div><div class="floating float-two">🏆 <strong>KidCode</strong><br><small>مسابقه و چالش پروژه‌ای</small></div></div></div></section>
<section class="stats"><div class="container stats-grid"><div class="stat"><strong>۴+</strong><span>مسیر آموزشی</span></div><div class="stat"><strong>پروژه</strong><span>یادگیری عملی</span></div><div class="stat"><strong>زنده</strong><span>کلاس آنلاین</span></div><div class="stat"><strong>🏆</strong><span>مسابقات</span></div></div></section>
<section id="courses" class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">مسیرهای یادگیری</span><h2>دوره‌های آموزشی</h2><p>دوره‌ای را انتخاب کن و قدم‌به‌قدم پیش برو.</p></div></div><div class="courses">
<div class="course"><div class="course-top">💻</div><div class="course-body"><h3>برنامه‌نویسی</h3><p>از پایه تا ساخت پروژه‌های واقعی.</p><div class="meta"><span>پروژه محور</span><span>شروع آسان</span></div></div></div>
<div class="course"><div class="course-top">👦</div><div class="course-body"><h3>Scratch Junior</h3><p>برنامه‌نویسی با داستان و بازی.</p><div class="meta"><span>مناسب کودکان</span><span>جذاب</span></div></div></div>
<div class="course"><div class="course-top">🤖</div><div class="course-body"><h3>هوش مصنوعی</h3><p>آشنایی کاربردی با دنیای AI.</p><div class="meta"><span>مدرن</span><span>پروژه‌ای</span></div></div></div>
<div id="kidcode" class="course"><div class="course-top">🏆</div><div class="course-body"><h3>مسابقات KidCode</h3><p>چالش، مسابقه و نمایش پروژه‌ها.</p><div class="meta"><span>مسابقه</span><span>هیجان‌انگیز</span></div></div></div>
</div></div></section>
<section class="section"><div class="container service-grid"><div class="service"><div class="service-icon">🎯</div><h3>مسیر اختصاصی</h3><p>هر دانش‌آموز می‌تواند دوره‌های مخصوص خودش را داشته باشد.</p></div><div class="service"><div class="service-icon">🔐</div><h3>دسترسی خصوصی</h3><p>محتوای دوره فقط برای کاربران مجاز نمایش داده می‌شود.</p></div><div class="service"><div class="service-icon">📈</div><h3>پیشرفت آموزشی</h3><p>ساختار سایت برای توسعه پنل دانش‌آموز آماده است.</p></div></div></section>
<section id="online" class="section"><div class="container"><div class="online"><div><span class="eyebrow">کلاس زنده</span><h2>کلاس آنلاین برای دانش‌آموزان ثبت‌نام‌شده</h2><p>بعد از راه‌اندازی سیستم عضویت، هر دانش‌آموز فقط به کلاس‌هایی که برایش فعال شده‌اند دسترسی خواهد داشت.</p><a class="btn btn-light" href="#">🔵 ورود به BigBlueButton</a></div><div class="online-box"><h3>🔐 کلاس خصوصی</h3><p>لینک کلاس می‌تواند فقط داخل پنل دانش‌آموز نمایش داده شود.</p></div></div></div></section>
</main><?php get_footer(); ?>